# enable Docker for your repository
options:
  docker: true

definitions:
  services:
    steps:
      - step: &build-and-push
          image: docker
          script:
            - apk add curl
            # build the image
            - export NXT_REGISTRY_URL=${NXT_REG_URL}/${BITBUCKET_REPO_SLUG}
            - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
            - docker login --username "${NXT_REG_USER}" --password "${NXT_REG_PASSWD}" ${NXT_REG_URL}
            - docker image build --build-arg GIT_COMMIT=${BITBUCKET_COMMIT} -t ${NXT_REGISTRY_URL}:$BUILD_ID -t ${NXT_REGISTRY_URL}:${BITBUCKET_BRANCH} .
            # push to repo
            - docker push ${NXT_REGISTRY_URL}:${BITBUCKET_BRANCH}
            - docker push ${NXT_REGISTRY_URL}:${BUILD_ID}
             # tag master image as latest
            - if [ ${BITBUCKET_BRANCH} == "master" ]; then docker tag ${NXT_REGISTRY_URL}:${BUILD_ID} ${NXT_REGISTRY_URL}:latest; docker push ${NXT_REGISTRY_URL}:latest; fi

pipelines:
  branches:
    dev:
      - step: *build-and-push
      - step:
          name: Deploy
          deployment: dev
          script:
            - curl -X POST ${PORTA_WH_DEV}
    stage:
      - step: *build-and-push
      - step:
          name: Deploy
          deployment: stage
          script:
            - curl -X POST ${PORTA_WH_STAGE}
    master:
      - step: *build-and-push
      - step:
          name: Deploy
          deployment: preprod
          script:
            - curl -X POST ${PORTA_WH_MASTER}

definitions:
  services:
    docker:
      memory: 3072
