# enable Docker for your repository
options:
  docker: true

pipelines:
  custom: # Pipelines that can only be triggered manually
    sonar:
      - step:
          script:
            - echo "Manual triggers for Sonar are awesome!"
    deployment-to-prod:
      - step:
          script:
            - echo "Manual triggers for deployments are awesome!"
  branches:
    master:
      - step:
          #python image with aws-cli installed
          image: docker
          script:
            - apk add curl
            # build the image
            - export NXT_REGISTRY_URL=${NXT_REG_URL}/${BITBUCKET_REPO_SLUG}
            - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
            - docker login --username "${NXT_REG_USER}" --password "${NXT_REG_PASSWD}" ${NXT_REG_URL}
            - docker image build --build-arg GIT_COMMIT=${BITBUCKET_COMMIT} -t ${NXT_REGISTRY_URL}:$BUILD_ID -t ${NXT_REGISTRY_URL}:latest .
            # push to repo
            - docker push ${NXT_REGISTRY_URL}:latest
            - docker push ${NXT_REGISTRY_URL}:$BUILD_ID
            # deploy to stagging site
            - curl -X POST ${UPDATE_WEBHOOK}
    dev:
      - step:
          image: docker
          script:
            - apk add curl
            # build the image
            - export NXT_REGISTRY_URL=${NXT_REG_URL}/${BITBUCKET_REPO_SLUG}
            - export BUILD_ID=$BITBUCKET_BRANCH_$BITBUCKET_COMMIT_$BITBUCKET_BUILD_NUMBER
            - docker login --username "${NXT_REG_USER}" --password "${NXT_REG_PASSWD}" ${NXT_REG_URL}
            - docker image build --build-arg GIT_COMMIT=${BITBUCKET_COMMIT} -t ${NXT_REGISTRY_URL}:$BUILD_ID -t ${NXT_REGISTRY_URL}:dev .
            # push to repo
            - docker push ${NXT_REGISTRY_URL}:dev
            - docker push ${NXT_REGISTRY_URL}:$BUILD_ID
            # deploy to stagging site
            - curl -X POST ${DEV_UPDATE_WEBHOOK}
        services:
          - docker
        caches:
          - docker
definitions:
  services:
    docker:
      memory: 3072
