export const RECEIVED_FETCH_STOREFRONT = 'RECEIVED_FETCH_STOREFRONT';
export const REQUEST_FETCH_STOREFRONT_SEO = 'REQUEST_FETCH_STOREFRONT_SEO';
export const RECIEVED_FETCH_STOREFRONT_SEO = 'RECIEVED_FETCH_STOREFRONT_SEO';
