export const REQUEST_CREATE_ORDER = 'REQUEST_CREATE_ORDER';
export const RECEIVED_CREATE_ORDER = 'RECEIVED_CREATE_ORDER';
export const REQUEST_FIND_ORDERS_BY_ACCOUNT = 'REQUEST_FIND_ORDERS_BY_ACCOUNT';
export const RECEIVED_FIND_ORDERS_BY_ACCOUNT = 'RECEIVED_FIND_ORDERS_BY_ACCOUNT';
