// Event-based architecture
export const FE_ORDER_CANCELLED = 'FE_ORDER_CANCELLED';
export const FE_ORDER_SUBMITTED = 'FE_ORDER_SUBMITTED';

export const RECEIVED_CREATE_ORDER_SUCCESS = 'RECEIVED_CREATE_ORDER_SUCCESS';
export const RECEIVED_CREATE_ORDER_FAILURE = 'RECEIVED_CREATE_ORDER_FAILURE';

export const RECEIVED_CANCEL_ORDER_SUCCESS = 'RECEIVED_CANCEL_ORDER_SUCCESS';
export const RECEIVED_CANCEL_ORDER_FAILURE = 'RECEIVED_CANCEL_ORDER_FAILURE';

export const REQUEST_FIND_ALL_ORDERS = 'REQUEST_FIND_ALL_ORDERS';
export const RECEIVED_FIND_ALL_ORDERS = 'RECEIVED_FIND_ALL_ORDERS';

export const REQUEST_FIND_ORDERS_BY_ACCOUNT = 'REQUEST_FIND_ORDERS_BY_ACCOUNT';

export const REQUEST_GET_ORDER = 'REQUEST_GET_ORDER';
export const RECEIVED_GET_ORDER = 'RECEIVED_GET_ORDER';

export const RESET_ORDER_STATE = 'RESET_ORDER_STATE';
