export const REQUEST_CREATE_ACCOUNT = 'REQUEST_CREATE_ACCOUNT';
export const RECEIVED_CREATE_ACCOUNT_SUCCESS =
  'RECEIVED_CREATE_ACCOUNT_SUCCESS';
export const RECEIVED_CREATE_ACCOUNT_FAILURE =
  'RECEIVED_CREATE_ACCOUNT_FAILURE';

export const REQUEST_FETCH_ACCOUNT = 'REQUEST_FETCH_ACCOUNT';
export const RECEIVED_FETCH_ACCOUNT_SUCCESS = 'RECEIVED_FETCH_ACCOUNT_SUCCESS';
export const RECEIVED_FETCH_ACCOUNT_FAILURE = 'RECEIVED_FETCH_ACCOUNT_FAILURE';

export const RECEIVED_FIND_ORDERS_BY_ACCOUNT =
  'RECEIVED_FIND_ORDERS_BY_ACCOUNT';

export const REQUEST_PATCH_ACCOUNT = 'REQUEST_PATCH_ACCOUNT';
export const RECEIVED_PATCH_ACCOUNT_SUCCESS = 'RECEIVED_PATCH_ACCOUNT_SUCCESS';
export const RECEIVED_PATCH_ACCOUNT_FAILURE = 'RECEIVED_PATCH_ACCOUNT_FAILURE';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVED_LOGIN_SUCCESS = 'RECEIVED_LOGIN_SUCCESS';
export const RECEIVED_LOGIN_FAILURE = 'RECEIVED_LOGIN_FAILURE';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';

export const REQUEST_FORGOT_PASSWORD = 'REQUEST_FORGOT_PASSWORD';
