export const REQUEST_FETCH_ACCOUNT = 'REQUEST_FETCH_ACCOUNT';
export const RECEIVED_FETCH_ACCOUNT = 'RECEIVED_FETCH_ACCOUNT';

export const REQUEST_PATCH_ACCOUNT = 'REQUEST_PATCH_ACCOUNT';
export const RECEIVED_PATCH_ACCOUNT = 'RECEIVED_PATCH_ACCOUNT';
