export const REQUEST_CREATE_ACCOUNT = 'REQUEST_CREATE_ACCOUNT';
export const RECEIVED_CREATE_ACCOUNT_SUCCESS = 'RECEIVED_CREATE_ACCOUNT_SUCCESS';
export const RECEIVED_CREATE_ACCOUNT_FAILURE = 'RECEIVED_CREATE_ACCOUNT_FAILURE';
export const CLEAR_CREATE_ACCOUNT_ERROR = 'CLEAR_CREATE_ACCOUNT_ERROR';

export const REQUEST_FETCH_ACCOUNT = 'REQUEST_FETCH_ACCOUNT';
export const RECEIVED_FETCH_ACCOUNT_SUCCESS = 'RECEIVED_FETCH_ACCOUNT_SUCCESS';
export const RECEIVED_FETCH_ACCOUNT_FAILURE = 'RECEIVED_FETCH_ACCOUNT_FAILURE';
export const CLEAR_FETCH_ACCOUNT_ERROR = 'CLEAR_FETCH_ACCOUNT_ERROR';

export const RECEIVED_FIND_ORDERS_BY_ACCOUNT = 'RECEIVED_FIND_ORDERS_BY_ACCOUNT';

export const REQUEST_PATCH_ACCOUNT = 'REQUEST_PATCH_ACCOUNT';
export const RECEIVED_PATCH_ACCOUNT_SUCCESS = 'RECEIVED_PATCH_ACCOUNT_SUCCESS';
export const RECEIVED_PATCH_ACCOUNT_FAILURE = 'RECEIVED_PATCH_ACCOUNT_FAILURE';
export const CLEAR_PATCH_ACCOUNT_ERROR = 'CLEAR_PATCH_ACCOUNT_ERROR';

export const REQUEST_CHANGE_PASSWORD = 'REQUEST_CHANGE_PASSWORD';
export const RECEIVED_CHANGE_PASSWORD_SUCCESS = 'RECEIVED_CHANGE_PASSWORD_SUCCESS';
export const RECEIVED_CHANGE_PASSWORD_FAILURE = 'RECEIVED_CHANGE_PASSWORD_FAILURE';
export const CLEAR_CHANGE_PASSWORD_ERROR = 'CLEAR_CHANGE_PASSWORD_ERROR';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVED_LOGIN_SUCCESS = 'RECEIVED_LOGIN_SUCCESS';
export const RECEIVED_LOGIN_FAILURE = 'RECEIVED_LOGIN_FAILURE';
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';

export const REQUEST_FORGOT_PASSWORD = 'REQUEST_FORGOT_PASSWORD';

export const REQUEST_SIGNUP_EMAIL = 'REQUEST_SIGNUP_EMAIL';

export const REQUEST_PASSWORD_RESET = 'REQUEST_RESET_PASSWORD';
export const RECEIVED_PASSWORD_RESET_SUCCESS = 'RECEIVED_RESET_PASSWORD_SUCCESS';
export const RECEIVED_PASSWORD_RESET_FAILURE = 'RECEIVED_RESET_PASSWORD_FAILURE';
export const CLEAR_PASSWORD_RESET_ERROR = 'CLEAR_PASSWORD_RESET_ERROR';

export const REQUEST_CHECK_EMAIL_EXISTENCE = 'REQUEST_CHECK_EMAIL_EXISTENCE';
export const RECEIVED_CHECK_EMAIL_EXISTENCE = 'RECEIVED_CHECK_EMAIL_EXISTENCE';

export const CLEAR_ACCOUNT_DATA = 'CLEAR_ACCOUNT_DATA';
