export const REQUEST_FETCH_CART = 'REQUEST_FETCH_CART';
export const RECEIVED_FETCH_CART = 'RECEIVED_FETCH_CART';

export const REQUEST_CREATE_CART = 'REQUEST_CREATE_CART';
export const RECEIVED_CREATE_CART = 'RECEIVED_CREATE_CART';

export const REQUEST_UPDATE_CART = 'REQUEST_UPDATE_CART';
export const RECEIVED_UPDATE_CART = 'RECEIVED_UPDATE_CART';

export const REQUEST_PATCH_CART = 'REQUEST_PATCH_CART';
export const RECEIVED_PATCH_CART = 'RECEIVED_PATCH_CART';

export const SET_CART_DRAWER_OPENED = 'SET_CART_DRAWER_OPENED';

export const REQUEST_REMOVE_CART_BY_ID = 'REQUEST_REMOVE_CART_BY_ID';

export const REQUEST_ADD_TO_CART = 'REQUEST_ADD_TO_CART';
export const REQUEST_REMOVE_FROM_CART = 'REQUEST_REMOVE_FROM_CART';
export const REQUEST_UPDATE_QUANTITY = 'REQUEST_UPDATE_QUANTITY';

export const REQUEST_MERGE_CARTS = 'REQUEST_MERGE_CARTS';

export const REQUEST_ADD_COUPON = 'REQUEST_ADD_COUPON';
export const REQUEST_REMOVE_COUPON = 'REQUEST_REMOVE_COUPON';

export const REQUEST_SET_SHIPPING_ADDRESS = 'REQUEST_SET_SHIPPING_ADDRESS';

export const RESET_CART = 'RESET_CART';