export const REQUEST_FETCH_CART = 'REQUEST_FETCH_CART';
export const RECEIVED_FETCH_CART = 'RECEIVED_FETCH_CART';

export const REQUEST_CREATE_CART = 'REQUEST_CREATE_CART';
export const RECEIVED_CREATE_CART = 'RECEIVED_CREATE_CART';

export const REQUEST_UPDATE_CART = 'REQUEST_UPDATE_CART';
export const RECEIVED_UPDATE_CART = 'RECEIVED_UPDATE_CART';

export const REQUEST_REMOVE_CART = 'REQUEST_REMOVE_CART';
export const RECEIVED_REMOVE_CART = 'RECEIVED_REMOVE_CART';

export const REQUEST_ADD_ITEM_CART = 'REQUEST_ADD_ITEM_CART';
export const RECEIVED_ADD_ITEM_CART = 'RECEIVED_ADD_ITEM_CART';

export const REQUEST_REMOVE_ITEM_CART = 'REQUEST_REMOVE_ITEM_CART';
export const RECEIVED_REMOVE_ITEM_CART = 'RECEIVED_REMOVE_ITEM_CART';

export const REQUEST_CLEAR_CART = 'REQUEST_CLEAR_CART';
export const RECEIVED_CLEAR_CART = 'RECEIVED_CLEAR_CART';

export const REQUEST_ADD_COUPON_CART = 'REQUEST_ADD_COUPON_CART';
export const RECEIVED_ADD_COUPON_CART = 'RECEIVED_ADD_COUPON_CART';

export const REQUEST_REMOVE_COUPON_CART = 'REQUEST_REMOVE_COUPON_CART';
export const RECEIVED_REMOVE_COUPON_CART = 'RECEIVED_REMOVE_COUPON_CART';