export const REQUEST_FETCH_CART = 'REQUEST_FETCH_CART';
export const RECEIVED_FETCH_CART = 'RECEIVED_FETCH_CART';

export const REQUEST_CREATE_CART = 'REQUEST_CREATE_CART';
export const RECEIVED_CREATE_CART = 'RECEIVED_CREATE_CART';

export const REQUEST_UPDATE_CART = 'REQUEST_UPDATE_CART';
export const RECEIVED_UPDATE_CART = 'RECEIVED_UPDATE_CART';

export const REQUEST_PATCH_CART = 'REQUEST_PATCH_CART';
export const RECEIVED_PATCH_CART = 'RECEIVED_PATCH_CART';

export const SET_CART_DRAWER_OPENED = 'SET_CART_DRAWER_OPENED';

export const REQUEST_FETCH_CART_BY_EMAIL = 'REQUEST_FETCH_CART_BY_EMAIL';
export const REQUEST_REMOVE_CART_BY_ID = 'REQUEST_REMOVE_CART_BY_ID';
