export const REQUEST_PRODUCT = 'REQUEST_FETCH_PRODUCT';
export const RECEIVED_PRODUCT = 'RECEIVED_FETCH_PRODUCT';
export const REQUEST_VARIANTS = 'REQUEST_FETCH_VARIANTS';
export const RECEIVED_VARIANTS = 'RECEIVED_FETCH_VARIANTS';