export * from './account';
export { default as LoginPage } from './Login';
export { default as SignupPage } from './Signup';
export { default as HomePage } from './Home';
export { default as StaticPage } from './Static';
export { default as GalleryPage } from './Gallery';
export { default as ProductPage } from './Product';
export { default as CartPage } from './Cart';
export { default as CheckoutPage } from './Checkout';
export { default as ForgotPassword } from './password/ForgotPassword';
export { default as ConfirmPassword } from './password/ConfirmPassword';
