export * from './account';
export { default as LoginPage } from './Login';
export { default as SignupPage } from './Signup';
export { default as HomePage } from './Home';
export { default as StaticPage } from './Static';
export { default as GalleryPage } from './Gallery';
export { default as ProductPage } from './Product';
export { default as OrderConfirmationPage } from './OrderConfirmation';
export { default as CheckoutPage } from './Checkout';
export { default as ForgotPassword } from './password/ForgotPassword';
export { default as ConfirmPassword } from './password/ConfirmPassword';
export { default as ResetPassword } from './password/ResetPassword';
export { default as ResetSuccess } from './password/ResetSuccess';
export { default as OrderPage } from './order/Order';
export { default as ContactUsPage } from './ContactUs';
export { default as FAQPage } from './FAQ';
export { default as Journal } from './Journal';
export { default as BlogPost } from './BlogPost';
