export const REQUEST_FETCH_PRODUCTS = 'REQUEST_FETCH_PRODUCTS';
export const RECEIVED_FETCH_PRODUCTS = 'RECEIVED_FETCH_PRODUCTS';
export const REQUEST_FETCH_PRODUCT = 'REQUEST_FETCH_PRODUCT';
export const RECEIVED_FETCH_PRODUCT = 'RECEIVED_FETCH_PRODUCT';
export const REQUEST_FETCH_VARIANTS = 'REQUEST_FETCH_VARIANTS';
export const RECEIVED_FETCH_VARIANTS = 'RECEIVED_FETCH_VARIANTS';